export const repoOsConfig = {
  currentContextFile: "docs/context/current-state.md",
  requiredCommands: ["node", "pnpm", "git"],
  requiredFiles: [
    "AGENTS.md",
    "CLAUDE.md",
    "CONTRIBUTING.md",
    ".github/copilot-instructions.md",
    ".github/pull_request_template.md",
    ".github/workflows/ci.yml",
    ".githooks/pre-commit",
    "lighthouserc.json",
    "package.json",
    "tsconfig.json",
    "biome.json",
    "knip.json",
    "dependency-cruiser.cjs",
    ".env.example",
    "docs/README.md",
    "docs/context/current-state.md",
    "docs/product/trial-brief.md",
    "docs/product/build-tracker.md",
    "next-env.d.ts",
    "next.config.ts",
    "postcss.config.mjs",
    "supabase/config.toml",
    "supabase/seed.sql",
    "docs/process/README.md",
    "docs/process/standards/README.md",
    "docs/process/templates/README.md",
    "docs/process/records/README.md",
  ],
  requiredDirs: [
    ".github/workflows",
    "app",
    "components/ui",
    "docs/context",
    "docs/process/records/intents",
    "docs/process/records/research",
    "docs/process/records/specs",
    "docs/process/records/validations",
    "docs/process/standards",
    "docs/process/templates",
    "features",
    "lib",
    "supabase",
    "tests/e2e",
    "tools/repo",
  ],
  ignoreGlobs: [
    ".git/**",
    ".lighthouseci/**",
    ".next/**",
    ".pnpm-store/**",
    "RepoBrainOs/**",
    "coverage/**",
    "dist/**",
    "node_modules/**",
    "playwright-report/**",
    "test-results/**",
  ],
  protectedGlobs: [
    ".github/**",
    ".githooks/**",
    "app/**",
    "components/**",
    "features/**",
    "lib/**",
    "middleware.*",
    "package.json",
    "playwright.config.*",
    "pnpm-lock.yaml",
    "postcss.config.*",
    "supabase/**",
    "tailwind.config.*",
    "tools/repo/**",
    "tsconfig.json",
  ],
  researchTriggerGlobs: [
    ".github/workflows/**",
    "docs/process/standards/**",
    "package.json",
    "playwright.config.*",
    "supabase/**",
    "tools/repo/**",
  ],
  sourceRoots: ["app", "components", "features", "lib", "supabase", "tests", "tools/repo"],
  sourceFileGlobs: [
    "app/**/*.{js,jsx,mjs,cjs,ts,tsx}",
    "components/**/*.{js,jsx,mjs,cjs,ts,tsx}",
    "features/**/*.{js,jsx,mjs,cjs,ts,tsx}",
    "lib/**/*.{js,jsx,mjs,cjs,ts,tsx}",
    "supabase/**/*.{js,jsx,mjs,cjs,ts,tsx}",
    "tests/**/*.{js,jsx,mjs,cjs,ts,tsx}",
    "tools/repo/**/*.{js,jsx,mjs,cjs,ts,tsx}",
  ],
  sizeExemptGlobs: [
    "**/*.config.*",
    "**/*.d.ts",
    "**/README.md",
    "supabase/generated/**",
    "supabase/migrations/**",
  ],
  forbiddenFolderNames: ["helpers", "misc", "temp", "utils"],
  limits: {
    maxFileLines: 300,
    maxReactFileLines: 220,
    maxFunctionLines: 60,
  },
  performanceBudgets: {
    mobilePerformanceScore: 90,
    accessibilityScore: 90,
    bestPracticesScore: 95,
    patientSearchInitialJsKbGzip: 160,
    bookingInitialJsKbGzip: 140,
    vendorDashboardInitialJsKbGzip: 180,
    patientSearchReadPaths: 1,
    bookingTransactionalWritePaths: 1,
    vendorBookingsReadPaths: 2,
  },
  routeBudgetTargets: [
    {
      label: "patientSearch",
      route: "/",
      manifestPath: ".next/server/app/page_client-reference-manifest.js",
      entryKey: "[project]/app/page",
      budgetKey: "patientSearchInitialJsKbGzip",
    },
    {
      label: "booking",
      route: "/booking",
      manifestPath: ".next/server/app/booking/page_client-reference-manifest.js",
      entryKey: "[project]/app/booking/page",
      budgetKey: "bookingInitialJsKbGzip",
    },
    {
      label: "vendorDashboard",
      route: "/vendor/dashboard",
      manifestPath: ".next/server/app/vendor/dashboard/page_client-reference-manifest.js",
      entryKey: "[project]/app/vendor/dashboard/page",
      budgetKey: "vendorDashboardInitialJsKbGzip",
    },
  ],
  dependencyJustifications: {
    "@tailwindcss/postcss":
      "Tailwind CSS v4 PostCSS integration for the Next.js app shell and future UI work.",
    "@biomejs/biome": "Machine-enforced formatting and linting baseline for repo quality.",
    "@lhci/cli":
      "Lighthouse CI support for performance and UX budget enforcement when app routes exist.",
    "@playwright/test": "Smoke and end-to-end browser checks for future patient and vendor flows.",
    "@supabase/supabase-js":
      "Server-side Supabase access for the real patient, booking, and vendor data flows.",
    "@types/node": "Type support for repo scripts and tests.",
    "@types/react": "React type support for the Next.js app and feature components.",
    "@types/react-dom": "React DOM type support for the Next.js app runtime.",
    "dependency-cruiser": "Boundary, dependency, and cycle enforcement for feature structure.",
    "framer-motion":
      "Measured motion primitives for the premium healthcare UI pass while keeping interaction logic isolated to client boundaries.",
    knip: "Unused file, export, and dependency detection to support less-code discipline.",
    next: "App Router runtime for the Rogveda product application.",
    postcss: "PostCSS runtime required for Tailwind CSS integration in the Next.js app shell.",
    react: "UI runtime for the Next.js app shell and future product features.",
    "react-dom": "DOM renderer for the Next.js app shell and future product features.",
    tailwindcss: "Utility-first styling baseline for fast, low-overhead product UI implementation.",
    typescript: "Strict typechecking baseline for repo tooling and future app code.",
    vitest: "Fast unit and automation tests for repo enforcement logic.",
    zod: "Boundary validation for environment configuration and future API contracts.",
  },
  syncIndexes: [
    {
      readme: "docs/process/standards/README.md",
      directory: "docs/process/standards",
    },
    {
      readme: "docs/process/templates/README.md",
      directory: "docs/process/templates",
    },
  ],
  mirrorChecks: [
    { file: "CLAUDE.md", mustInclude: ["AGENTS.md"] },
    { file: ".github/copilot-instructions.md", mustInclude: ["AGENTS.md"] },
  ],
};
